{
 "title": "Great Beer Challenge Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "GetBeers method duration average",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "method_duration_sum{get_method_full_name=\"BeerController.getBeers\",service=\"beer-service\"} / method_duration_count{get_method_full_name=\"BeerController.getBeers\",service=\"beer-service\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "system_cpu_usage{service=\"gui-service\"} * 100"
    }
   ]
  },
  {
   "title": "beer-service number of calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_in_count{service=\"beer-service\"}[30s]"
    }
   ]
  },
  {
   "title": "JVM usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "(jvm_memory_used{id=\"Code Cache\",service=\"beer-service\"} * 100 ) / jvm_memory_max{id=\"Code Cache\",service=\"beer-service\"}"
    },
    {
     "expr": "(jvm_memory_used{id=\"Survivor Space\",service=\"beer-service\"} * 100 ) / jvm_memory_max{id=\"Survivor Space\",service=\"beer-service\"}"
    },
    {
     "expr": "(jvm_memory_used{id=\"Eden Space\",service=\"beer-service\"} * 100 ) / jvm_memory_max{id=\"Eden Space\",service=\"beer-service\"}"
    }
   ]
  }
 ]
}